### PR TITLE
added Crypto Jobs List (https://cryptojobslist.com/)

### PR DESCRIPTION
**Pull request by ksaitor**

### CODE REVIEW

**Comment by ksaitor** [comment]
ups… looks like i've got to work on my alphabet skills… 🤔
… somehow i thought that `C` goes before `B`

Doctor, will this be pull request be fine?

**Comment by wfhio** [comment]
Hi @ksaitor !  Can you please switch the ordering?  Also, if you rebase against master the Travis CI test should pass (I fixed the lint failures in https://github.com/wfhio/awesome-job-boards/pull/37).

Thank you -- and give me a shout if you have any questions!

**Comment by ksaitor** [comment]
@wfhio pushed re-ordered code. Anything else I should do?

**Comment by ksaitor** [comment]
🍻

**Pull request merged**
